partials/content-cta.hbs, partials/cover.hbs, partials/header.hbs
=> Remove login sub links

README.md, partials/header.hbs
This closes https://github.com/AdvisorySG/dawn-advisory-theme/issues/6. See below for screenshots:
=> Set up search

assets/css/blog/single.css, partials/content.hbs
This PR changes the placement of the featured image to be in line with how the Ghost post editor displays the featured image.
=> Post: Change placement of featured image to above title

assets/css/blog/quotes.css, assets/css/screen.css, assets/js/main.js, home.hbs, partials/quotes.hbs
Things done
1. Followed advisory.sg and copied the quotes over, put in a separate partial
2. Did some custom styling for the bullet points (the default glide theme had white/transparent buttons which was not really visible, so I didn't import it)
=> Quotes slider

assets/js/main.js, package.json
Replaced the search results from elasticlunr (which doesn't work on my system for some reason) with ElasticSearch (which does work). API Key used is mine
XMLHttpRequest used to retrieve data from the endpoint, no need for external libraries.
Code will be cleaned up soon
=> Replace Elasticlunr with ElasticSearch

partials/content-cta.hbs
encountered this small error when setting up, think it should work now
=> changed products to tiers so can upload zip to Ghost

partials/post-card.hbs
=> Changing element of no-tag

error.hbs
Closes https://github.com/AdvisorySG/dawn-advisory-theme/issues/128 with the custom 404 page that @nicholasohjj created.
=> error: Initial commit

assets/css/site/search.css, assets/js/main.js
=> Search Keyboard Navigation

assets/js/main.js
Added a tooltip to provide more info if needed
=> Search Excerpt with bolding of query

partials/related.hbs
Reduced the no. of related posts to 3.
=> reduced the no. of related post

.djlintrc, .github/workflows/lint.yml, package.json, page-impact.hbs, partials/content.hbs, partials/footer.hbs, partials/our-programmes.hbs, partials/related.hbs, tag.hbs
While djLint has a [formatter](https://www.djlint.com/docs/formatter/), the formatter does not produce good results on more complex pages and does not output fatal errors when formatting, unlike Prettier, leading to some pages being formatted even when they had broken syntax.
=> Add djLint for .hbs linting

assets/css/site/sticky.css
=> Bigger Progress Bar

assets/js/main.js
1. I did not find the first scenario issue.
2. the second scenario issue is solved by adding "ArrowLeft" and "ArrowRight" cases.
=> fixed the issue

assets/css/blog/single.css, partials/post-card.hbs
Not sure if my CSS is in the right file but yea. Just put there.
=> posts shows url on hover

default.hbs, package.json, partials/header.hbs
fix issue 170 - search bar does not appear when screen is fully maximised
=> fix issue 170 on disappearing search bar

assets/js/main.js
=> Search Query Highlighting in title & description

assets/css/site/modal.css, assets/css/site/search.css, assets/js/main.js, partials/modal.hbs, partials/search-pagination.hbs
Added the pagination. I think it looks pretty good.
Also fixed a bug where clearing input with the x button doesn't reset the search.
=> [GPT-15] Pagination for search

page-events.hbs
Changed the events page to use a loxi events widget instead of the elfsight widget
=> [GPT-23] Events: loxi events widget sample

assets/css/blog/featured.css, assets/js/main.js, partials/featured.hbs, tailwind.config.js
Made into a single post with excerpt and tags above similar to the example given.
Also made the background mid-grey to stand out from the rest of the page.
=> [GPT-16] Single featured post

partials/footer.hbs
fixed https://github.com/AdvisorySG/dawn-advisory-theme/issues/268
=> [GPT-36] Add footer links

assets/css/blog/team.css, assets/js/main.js, package.json, page-team.hbs
1. page-team.hbs did not use class from team.css, it uses pure tailwind style instead
2. can consider other ways to reduce code duplication
=> [GPT-3] Team: Initial commit

partials/featured.hbs, partials/footer.hbs
make the featured post image go above the text if the view width is below md size
=> [GPT-37] Fix mobile homepage

assets/js/main.js
Fixed the auto scroll issue which caused more than 1 post to be displayed on screen.
=> [GPT-41] Featured Articles View is Ugly

partials/our-programmes.hbs
=> [GPT-11] Home: Redesign banners

assets/css/site/search.css, assets/js/main.js
=> [GPT-30] Search: Modal is not responsive on mobile

page-impact.hbs
=> [GPT-42] Removed the featured by

assets/css/blog/featured.css
=> [GPT-60] Increase size of Featured Article Image in Mobile View

partials/post-card.hbs
Replaced the blue border with gray border
=> [GPT-44] Stories: Blue Border on cards

assets/css/blog/featured.css
change post title font size from 1.8rem to 3.2rem
https://github.com/AdvisorySG/dawn-advisory-theme/issues/339
=> [GPT-82] make featured title bigger

assets/css/screen.css, assets/css/site/dropdown.css, assets/js/main.js
Added the dropdowns with the animation.
Closes #349 
Looks like this now
=> [GPT-90] Post: Retain toggle dropdown for H2 headings

README.md, assets/js/main.js
Bullet points and other elements are now also part of the dropdowns.
Closes #400
=> [GPT-127] fixed dropdown bug for bullet points

.devcontainer/devcontainer.json, assets/css/screen.css, assets/css/site/footnotes.css
=> [GPT-88] feat: update footnotes styling 

assets/css/blog/single.css, post.hbs
Changes the word errors to error
=> [GPT-151] Update post.hbs

assets/js/main.js
Seems to be related to this feature
https://github.com/AdvisorySG/dawn-advisory-theme/issues/460
=> feat: added duplicate tags support when filtering
